# Generated by Django 3.2.6 on 2022-11-02 07:11

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='atk',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='cnt_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='hp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='level_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='number_sheet_limit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='party_num',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='stk',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='text',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='number',
            field=models.CharField(max_length=500),
        ),
    ]
