# Generated by Django 3.2.6 on 2022-11-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_app', '0002_alter_cardinfo_rarelity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='typeof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card_app.typeof'),
        ),
    ]
