# Generated by Django 3.2.6 on 2022-11-13 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_app', '0003_auto_20221102_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_typeof', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('number', models.CharField(max_length=500)),
                ('rarelity', models.IntegerField(default=0, null=True)),
                ('name_japan', models.CharField(max_length=500)),
                ('kana', models.CharField(max_length=500)),
                ('rubi', models.CharField(max_length=500)),
                ('party', models.CharField(max_length=500)),
                ('attribute', models.CharField(max_length=500)),
                ('attribute2', models.CharField(max_length=500)),
                ('attribute3', models.CharField(max_length=500)),
                ('attribute4', models.CharField(max_length=500)),
                ('lv', models.IntegerField(default=0, null=True)),
                ('atk', models.IntegerField(default=0, null=True)),
                ('hp', models.IntegerField(default=0, null=True)),
                ('stk', models.IntegerField(default=0, null=True)),
                ('leftup', models.CharField(max_length=500)),
                ('leftdown', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=2500)),
                ('cnt', models.CharField(max_length=2500)),
                ('flaver_text', models.CharField(max_length=2500)),
                ('typeof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_app.typeof')),
            ],
        ),
    ]
