# Generated by Django 3.2.6 on 2022-11-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_app', '0003_alter_cardinfo_typeof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='atk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='lv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='stk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
